language: objective-c
osx_image: xcode7

install:
    - git submodule update -i --recursive

script:
- xctool -project Basis.xcodeproj -scheme Basis -sdk macosx ONLY_ACTIVE_ARCH=NO clean build test
- xctool -project Basis.xcodeproj -scheme Basis-iOS -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO clean build test
