language: objective-c
osx_image: xcode7

before_install:
    - gem install xcpretty-travis-formatter --no-rdoc --no-ri --no-document --quiet

install:
    - git submodule update -i --recursive

script:
    - set -o pipefail && xcodebuild -project Basis.xcodeproj -scheme Basis -sdk macosx ONLY_ACTIVE_ARCH=NO clean build test | xcpretty -c -f `xcpretty-travis-formatter`
    - set -o pipefail && xcodebuild -project Basis.xcodeproj -scheme Basis-iOS -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO clean build test | xcpretty -c -f `xcpretty-travis-formatter`
